[package]
name = "histrion"
version = "0.1.0"
edition = "2018"

[dependencies]
ordered-float = "1.0.2"
slotmap = "0.4.0"
vek = "0.9.12"

[dependencies.specs]
version = "0.16.1"
features = ["specs-derive"]
